functionsDirectory = "/Users/MacBook/SaaS/netlify/functions"
functionsDirectoryOrigin = "config-v1"
plugins = []
headers = []
redirects = []

[build]
publish = "/Users/MacBook/SaaS/build"
publishOrigin = "config"
base = "/Users/MacBook/SaaS"
command = "npm run build"
commandOrigin = "ui"
functions = "/Users/MacBook/SaaS/netlify/functions"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[functions]

[functions."*"]
node_bundler = "esbuild"